const header = document.querySelector(".site-header"), menuToggle = document.querySelector(".menu-toggle"), navLinks = document.querySelector(".nav-links"), cursorGlow = document.querySelector(".cursor-glow");
window.addEventListener("scroll", () => header.classList.toggle("scrolled", window.scrollY > 30));
menuToggle.addEventListener("click", () => { const open = menuToggle.classList.toggle("open"); navLinks.classList.toggle("open", open); menuToggle.setAttribute("aria-expanded", String(open)); menuToggle.setAttribute("aria-label", open ? "إغلاق القائمة" : "فتح القائمة") });
navLinks.querySelectorAll("a").forEach(link => link.addEventListener("click", () => { navLinks.classList.remove("open"); menuToggle.classList.remove("open"); menuToggle.setAttribute("aria-expanded", "false") }));
if (matchMedia("(pointer: fine)").matches) window.addEventListener("pointermove", event => { cursorGlow.style.left = `${event.clientX}px`; cursorGlow.style.top = `${event.clientY}px` });
document.querySelectorAll("[data-delay]").forEach(el => el.style.setProperty("--delay", `${el.dataset.delay}ms`));
const revealObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("visible"); revealObserver.unobserve(entry.target) } }), { threshold: .12 });
document.querySelectorAll(".reveal").forEach(el => revealObserver.observe(el));
const sections = [...document.querySelectorAll("main section[id]")], navigationItems = [...document.querySelectorAll(".nav-links a")];
const sectionObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) navigationItems.forEach(item => item.classList.toggle("active", item.hash === `#${entry.target.id}`)) }), { rootMargin: "-35% 0px -55%", threshold: 0 }); sections.forEach(section => sectionObserver.observe(section));

const floatingHearts = document.querySelector(".floating-hearts");
function releaseHeart() { if (document.hidden || matchMedia("(prefers-reduced-motion: reduce)").matches) return; const heart = document.createElement("span"); heart.className = "float-heart"; heart.textContent = Math.random() > .25 ? "♥" : "✦"; heart.style.left = `${Math.random() * 100}%`; heart.style.fontSize = `${.65 + Math.random() * .85}rem`; heart.style.setProperty("--duration", `${6 + Math.random() * 4}s`); heart.style.setProperty("--drift", `${-50 + Math.random() * 100}px`); floatingHearts.appendChild(heart); heart.addEventListener("animationend", () => heart.remove()) } setInterval(releaseHeart, 1300);
function bindDialog(dialog) { dialog.querySelector(".modal-close").addEventListener("click", () => dialog.close()); dialog.addEventListener("click", event => { if (event.target === dialog) dialog.close() }); dialog.addEventListener("close", () => document.body.classList.remove("modal-open")) }
const lightbox = document.querySelector("#lightbox"), lightboxImage = lightbox.querySelector("img"), lightboxCaption = lightbox.querySelector("figcaption"); bindDialog(lightbox);
document.querySelectorAll(".photo-card").forEach(card => card.addEventListener("click", () => { lightboxImage.src = card.dataset.image; lightboxImage.alt = card.querySelector("img").alt; lightboxCaption.textContent = card.dataset.caption; lightbox.showModal(); document.body.classList.add("modal-open") }));
const surpriseModal = document.querySelector("#surprise-modal"); bindDialog(surpriseModal); document.querySelectorAll(".surprise-trigger").forEach(trigger => trigger.addEventListener("click", () => { surpriseModal.showModal(); document.body.classList.add("modal-open"); for (let i = 0; i < 12; i++)setTimeout(releaseHeart, i * 90) }));
document.querySelector(".back-top").addEventListener("click", () => scrollTo({ top: 0, behavior: "smooth" }));

// Snake of Love
const canvas = document.querySelector("#snake-canvas"), context = canvas.getContext("2d"), startButton = document.querySelector("#start-game"), pauseButton = document.querySelector("#pause-game"), scoreElement = document.querySelector("#score"), bestScoreElement = document.querySelector("#best-score"), gameMessage = document.querySelector("#game-message"), gridSize = 20, tileCount = canvas.width / gridSize;
let snake = [], heart = { x: 14, y: 10 }, direction = { x: -1, y: 0 }, nextDirection = { x: -1, y: 0 }, score = 0, bestScore = Number(localStorage.getItem("loveSnakeBest") || 0), gameTimer = null, running = false, paused = false;
bestScoreElement.textContent = String(bestScore).padStart(2, "0");
function resetGame() { snake = [{ x: 10, y: 10 }, { x: 11, y: 10 }, { x: 12, y: 10 }]; direction = { x: -1, y: 0 }; nextDirection = { ...direction }; score = 0; scoreElement.textContent = "00"; placeHeart(); drawGame() }
function placeHeart() { do { heart = { x: Math.floor(Math.random() * tileCount), y: Math.floor(Math.random() * tileCount) } } while (snake.some(segment => segment.x === heart.x && segment.y === heart.y)) }
function roundedRect(x, y, w, h, r) { context.beginPath(); context.roundRect(x, y, w, h, r); context.fill() }
function drawHeart(x, y, size) { context.save(); context.translate(x, y); context.beginPath(); context.moveTo(0, size * .3); context.bezierCurveTo(-size, -size * .35, -size * .62, -size, 0, -size * .45); context.bezierCurveTo(size * .62, -size, size, -size * .35, 0, size * .3); context.fillStyle = "#df563d"; context.shadowColor = "rgba(223,86,61,.4)"; context.shadowBlur = 12; context.fill(); context.restore() }
function drawGame() { context.fillStyle = "#fffaf5"; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = "rgba(141,36,73,.055)"; for (let row = 0; row < tileCount; row++)for (let col = 0; col < tileCount; col++)if ((row + col) % 2 === 0) context.fillRect(col * gridSize, row * gridSize, gridSize, gridSize); drawHeart(heart.x * gridSize + gridSize / 2, heart.y * gridSize + gridSize / 2 + 2, 7); snake.forEach((segment, index) => { context.fillStyle = index === 0 ? "#641530" : `hsl(${338 + index * 1.8} 58% ${34 + Math.min(index, 9)}%)`; roundedRect(segment.x * gridSize + 2, segment.y * gridSize + 2, gridSize - 4, gridSize - 4, 6); if (index === 0) { context.fillStyle = "#fff"; const eyeX = direction.y !== 0 ? 5 : direction.x < 0 ? 5 : 12; context.beginPath(); context.arc(segment.x * gridSize + eyeX, segment.y * gridSize + 7, 1.6, 0, Math.PI * 2); context.arc(segment.x * gridSize + eyeX, segment.y * gridSize + 13, 1.6, 0, Math.PI * 2); context.fill() } }) }
function gameOver() { running = false; clearInterval(gameTimer); gameTimer = null; if (score > bestScore) { bestScore = score; localStorage.setItem("loveSnakeBest", String(bestScore)); bestScoreElement.textContent = String(bestScore).padStart(2, "0") } gameMessage.innerHTML = `<span>♡</span><strong>حلوة المحاولة!</strong><small>جمعتي ${score} ${score === 1 ? "قلب" : "قلوب"} — اضغطي للعب من جديد</small>`; gameMessage.classList.remove("hidden"); startButton.firstChild.textContent = "العبي من جديد " }
function tick() { direction = { ...nextDirection }; const head = { x: snake[0].x + direction.x, y: snake[0].y + direction.y }, hitWall = head.x < 0 || head.x >= tileCount || head.y < 0 || head.y >= tileCount, hitSelf = snake.some(segment => segment.x === head.x && segment.y === head.y); if (hitWall || hitSelf) { gameOver(); return } snake.unshift(head); if (head.x === heart.x && head.y === heart.y) { score++; scoreElement.textContent = String(score).padStart(2, "0"); placeHeart() } else snake.pop(); drawGame() }
function startGame() { clearInterval(gameTimer); resetGame(); running = true; paused = false; pauseButton.textContent = "Ⅱ"; gameMessage.classList.add("hidden"); startButton.firstChild.textContent = "إعادة اللعبة "; gameTimer = setInterval(tick, 115) }
function togglePause() { if (!running && !paused) return; paused = !paused; running = !paused; pauseButton.textContent = paused ? "▶" : "Ⅱ"; if (paused) { clearInterval(gameTimer); gameTimer = null; gameMessage.innerHTML = "<span>♥</span><strong>استراحة صغيرة</strong><small>اضغطي تشغيل للمتابعة</small>"; gameMessage.classList.remove("hidden") } else { gameMessage.classList.add("hidden"); gameTimer = setInterval(tick, 115) } }
function changeDirection(newDirection) { const directions = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } }, selected = directions[newDirection]; if (!selected || (selected.x === -direction.x && selected.y === -direction.y)) return; nextDirection = selected }
startButton.addEventListener("click", startGame); pauseButton.addEventListener("click", togglePause);
document.addEventListener("keydown", event => { const keyMap = { ArrowUp: "up", ArrowDown: "down", ArrowLeft: "left", ArrowRight: "right" }; if (!keyMap[event.key] || document.activeElement?.matches("input, textarea")) return; event.preventDefault(); changeDirection(keyMap[event.key]) });
document.querySelectorAll("[data-direction]").forEach(button => button.addEventListener("pointerdown", event => { event.preventDefault(); changeDirection(button.dataset.direction) }));
let touchStart = null; canvas.addEventListener("touchstart", event => { touchStart = { x: event.touches[0].clientX, y: event.touches[0].clientY } }, { passive: true }); canvas.addEventListener("touchend", event => { if (!touchStart) return; const dx = event.changedTouches[0].clientX - touchStart.x, dy = event.changedTouches[0].clientY - touchStart.y; if (Math.max(Math.abs(dx), Math.abs(dy)) < 20) return; changeDirection(Math.abs(dx) > Math.abs(dy) ? dx > 0 ? "right" : "left" : dy > 0 ? "down" : "up"); touchStart = null }, { passive: true });
resetGame();
